[package]
name = "bee-troika"
version = "0.1.0"
authors = ["IOTA Foundation"]
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = "0.2"
rand = "0.7"

[[bench]]
name = "troika_benchmark"
harness = false

[features]
troika = []